config/routes.rb
FbGraphSample::Application.routes.draw do
  # Canvas App
  resource :canvas, :only => [:show, :create]
  resource :credit, :only => :create
  resources :achievements, :only => [:index, :show, :new, :create]

  # Connect Site
  resource :facebook, :except => :create do
    get :callback, :to => :create
  end
  resource :dashboard, :only => :show
  resource :profile, :only => :show
  resource :timeline, :only => [:show, :create]
  resources :subscriptions, :only => [:index, :show, :create]
  post 'subscriptions/:id', :to => 'subscriptions#update'

  root :to => 'top#index'
end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  validates :title, :description, :image_url, :presence => true
  validates :points, :presence => true, :inclusion => {:in => 1..100}
end

app/models/facebook.rb
class Facebook < ActiveRecord::Base
  has_many :subscriptions

  def profile
    @profile ||= FbGraph::User.me(self.access_token).fetch
  end

  class << self
    extend ActiveSupport::Memoizable

    def config
      @config ||= if ENV['fb_client_id'] && ENV['fb_client_secret'] && ENV['fb_scope'] && ENV['fb_canvas_url']
        {
          :client_id     => ENV['fb_client_id'],
          :client_secret => ENV['fb_client_secret'],
          :scope         => ENV['fb_scope'],
          :canvas_url    => ENV['fb_canvas_url']
        }
      else
        YAML.load_file("#{Rails.root}/config/facebook.yml")[Rails.env].symbolize_keys
      end
    rescue Errno::ENOENT => e
      raise StandardError.new("config/facebook.yml could not be loaded.")
    end

    def app
      FbGraph::Application.new config[:client_id], :secret => config[:client_secret]
    end

    def auth(redirect_uri = nil)
      FbGraph::Auth.new config[:client_id], config[:client_secret], :redirect_uri => redirect_uri
    end

    def identify(fb_user)
      _fb_user_ = find_or_initialize_by_identifier(fb_user.identifier.try(:to_s))
      _fb_user_.access_token = fb_user.access_token.access_token
      _fb_user_.save!
      _fb_user_
    end
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :facebook

  validates :facebook, :object, :fields, :history_json, :verify_token, :presence => true

  before_validation :setup, :on => :create

  def history
    JSON.parse(self.history_json)
  end

  def history=(history)
    self.history_json = history.to_json
  end

  def subscribe!(callback)
    Facebook.app.subscribe!(
      :object => self.object,
      :fields => self.fields,
      :callback_url => callback,
      :verify_token => self.verify_token
    )
  end

  private

  def setup
    self.verify_token = ActiveSupport::SecureRandom.hex(16)
    self.history = []
  end

end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_filter :require_authentication, :except => :show

  def index
    @achievements = Achievement.all
  end

  def show
    @achievement = Achievement.find params[:id]
  end

  def new
    @achievement = Achievement.new
  end

  def create
    @achievement = Achievement.new params[:achievement]
    if @achievement.save
      redirect_to achievement_url(@achievement)
    else
      render :new
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  protect_from_forgery

  rescue_from FbGraph::Exception, :with => :fb_graph_exception

  def fb_graph_exception(e)
    flash[:error] = {
      :title   => e.class,
      :message => e.message
    }
    current_user.try(:destroy)
    redirect_to root_url
  end

end

app/controllers/canvas_controller.rb
class CanvasController < ApplicationController
  def show
    redirect_to Facebook.config[:canvas_url]
  end

  def create
    @auth = Facebook.auth.from_signed_request(params[:signed_request])
    if @auth.authorized?
      authenticate Facebook.identify(@auth.user)
      render :show
    else
      render :authorize
    end
  end
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  def create
    req = Facebook.auth.from_signed_request(params[:signed_request])
    order = req.data[:credits]
    res = case params[:method]
    when 'payments_get_items'
      {
        :content => [{
          :title       => "Donation to fb_graph",
          :description => "Thanks for your donation!",
          :price       => 2,
          :image_url   => "http://www.facebook.com/images/gifts/21.png",
          :product_url => "http://www.facebook.com/images/gifts/21.png"
        }]
      }
    when 'payments_status_update'
      {
        :content => {
          :order_id => order[:order_id],
          :status => :settled
        }
      }
    end
    res[:method] = params[:method]
    logger.info res.to_json
    render :json => res
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :require_authentication

  def show
  end

end

app/controllers/facebooks_controller.rb
require 'rack/oauth2'

class FacebooksController < ApplicationController
  before_filter :require_authentication, :only => :destroy

  rescue_from Rack::OAuth2::Client::Error, :with => :oauth2_error

  # handle Facebook Auth Cookie generated by JavaScript SDK
  def show
    auth = Facebook.auth.from_cookie(cookies)
    authenticate Facebook.identify(auth.user)
    redirect_to dashboard_url
  end

  # handle Normal OAuth flow: start
  def new
    client = Facebook.auth(callback_facebook_url).client
    redirect_to client.authorization_uri(
      :scope => Facebook.config[:scope]
    )
  end

  # handle Normal OAuth flow: callback
  def create
    client = Facebook.auth(callback_facebook_url).client
    client.authorization_code = params[:code]
    access_token = client.access_token! :client_auth_body
    user = FbGraph::User.me(access_token).fetch
    authenticate Facebook.identify(user)
    redirect_to dashboard_url
  end

  def destroy
    unauthenticate
    redirect_to root_url
  end

  private

  def oauth2_error(e)
    flash[:error] = {
      :title => e.response[:error][:type],
      :message => e.response[:error][:message]
    }
    redirect_to root_url
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_filter :require_authentication

  def show
    @posts = current_user.friends
  end

  def create
    current_user.profile.feed!(
      :message => params[:message]
    )
    redirect_to timeline_url
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :require_authentication

  def show
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :require_authentication, :only => [:index, :create]

  def index
  end

  # for Subscription Verification
  def show
    subscription = Subscription.find(params[:id])
    if subscription.verify_token == params[:'hub.verify_token']
      render :text => params[:'hub.challenge']
    else
      render :text => 'verify_token invalid', :status => 401
    end
  end

  def create
    subscription = current_user.subscriptions.build(params[:subscription])
    if subscription.save
      subscription.subscribe! subscription_url(subscription)
    else
      flash[:error] = {
        :title   => 'Invalid',
        :message => subscription.errors.full_messages.to_sentence
      }
    end
    redirect_to subscriptions_url
  end

  # for Change Notifications
  def update
    subscription = Subscription.find(params[:id])
    subscription.history = Array(subscription.history) + Array(params[:entry])
    subscription.save
    render :nothing => true
  end

end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
  before_filter :require_authentication

  def show
    @posts = current_user.profile.home
  end

  def create
    current_user.profile.feed!(
      :message => params[:message]
    )
    redirect_to timeline_url
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    redirect_to dashboard_url if authenticated?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Authentication::HelperMethods

  def fb_graph_url
    'http://github.com/nov/fb_graph'
  end

  def fb_graph_sample_url
    'http://github.com/nov/fb_graph_sample'
  end

end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/achievements/index.html.erb
<article>
  <h2>Achievements</h2>
  <ul>
    <% @achievements.each do |achievement| %>
      <li><%= link_to achievement.title, achievement_path(achievement) %></li>
    <% end %>
  </ul>
  <nav>
    <%= link_to 'Register new one', new_achievement_path %>
  </nav>
</article>

app/views/achievements/new.html.erb
<%= form_for @achievement do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :image_url, 'Image URL' %>
    <%= f.url_field :image_url %>
  </div>
  <div>
    <%= f.label :points, 'Points (0-100)' %>
    <%= f.number_field :points %>
  </div>
  <%= f.submit %>
<% end %>

app/views/achievements/show.html.erb
<% content_for :head do %>
  <meta property="og:title" content="<%= @achievement.title %>">
  <meta property="og:description" content="<%= @achievement.description %>">
  <meta property="og:type" content="game.achievement">
  <meta property="og:url" content="<%= achievement_url(@achievement) %>">
  <meta property="og:image" content="<%= @achievement.image_url %>">
  <meta property="og:points" content="<%= @achievement.points %>">
  
<% end %>

<article>
  <h2><%= @achievement.title %> - <%= @achievement.points %> [pts]</h2>
  <p><%= @achievement.description %></p>
  <%= image_tag @achievement.image_url %>
</article>

app/views/canvas/authorize.html.erb
<script>
  top.location.href = '<%= @auth.authorize_uri(canvas_url).html_safe %>';
</script>

app/views/canvas/show.html.erb
<article class='canvas'>
  <h2>Hello <fb:name uid='<%= current_user.identifier %>' useyou='false'></fb:name>!</h2>
  <p>Try Facebook Credit?</p>
  <nav>
    <%= link_to 'Donate to fb_graph using Facebook Credit :)', '#', :class => 'pay_now' %>
  </nav>
</article>

<script>
  $(function () {
    $('a.pay_now').click(function () {
      FB.ui({
        method: 'pay',
        order_info: 'Donation to fb_graph'
      });
      return false;
    });
  });
</script>

app/views/dashboard/show.html.erb
<section class='dashboard'>
  <h2>Hello <fb:name uid='<%= current_user.identifier %>' useyou='false'></fb:name>!</h2>
  <article>
    <h3><%= link_to 'Profile Details', profile_path %></h3>
    <p>User profile.</p>
  </article>
  <article>
    <h3><%= link_to 'Timeline (News Feed)', timeline_path %></h3>
    <p>Show your timeline and update status.</p>
  </article>
  <article>
    <h3><%= link_to 'Friend', friend_path %></h3>
    <p>Show all your Friend.</p>
  </article>
  <article>
    <h3><%= link_to 'Canvas App', canvas_path %></h3>
    <p>This link let you go to fb_graph's sample canvas app on apps.facebook.com.</p>
  </article>
  <article>
    <h3><%= link_to 'Subscription', subscriptions_path %></h3>
    <p>Subscribe your user's activity.</p>
    <p>This functionality is for developers, not for end-users.</p>
    <p>This page won't return any content to your browsers, since this endpoint is designed to respond to subscription verification request from facebook.com</p>
  </article>
  <article>
    <h3><%= link_to 'App Request', '#', :id => :app_request %></h3>
    <p>Send application requests to your friends.</p>
    <p>This functionality is for iframe applications running on apps.facebook.com domain.</p>
  </article>
</nav>

<script>
$(function () {
  $('#app_request').click(function () {
    FB.ui({
      method: 'apprequests',
      message: 'You should learn more about this awesome game.',
      filters: ['app_non_users'],
      data: 'tracking information for the user'
    });
  });
});
</script>

app/views/friends/show.html.erb
<section class="timeline">
  <% form_tag timeline_path do %>
    <%= text_area_tag :message, nil, :placeholder => 'Message here.' %>
    <%= submit_tag 'Update', :disable_with => 'Updating...' %>
  <% end %>
  <% @posts.each do |post| %>
    <article class="clearfix">
      <div class="avatar">
        <fb:profile-pic uid="<%= post.from.identifier %>" size="square"></fb:profile-pic>
      </div>
      <p>
        <strong><fb:name uid="<%= post.from.identifier %>"></fb:name></strong>
        <%= post.name %>
      </p>
    </article>
  <% end %>
</section>

app/views/layouts/_footer.html.erb
<footer>
  <ul>
    <li><small class="copytight">&copy; 2010-<%= Time.now.year %> <a href="http://matake.jp">nov matake</a></small></li>
    <li>
      Donation? Then, <%= link_to 'please help testing my PayPal Express gem with your $1', 'https://paypal-express-sample.heroku.com' %> ;)
    </li>
  </ul>
</footer>

app/views/layouts/_sidebar.html.erb
<div class="avatar">
  <fb:profile-pic uid="<%= current_user.try(:identifier) %>" size="normal" facebook-logo="true"></fb:profile-pic>
</div>

<% if authenticated? %>
  <p><%= link_to "Logout", facebook_path, :method => :delete %></p>
<% else %>
  <dl>
    <dt>JavaScript SDK</dt>
    <dd><fb:login-button length="long" onlogin="location.href = '<%= facebook_path %>'" scope="<%= Facebook.config[:scope] %>"></fb:login-button></dd>
    <dt>Normal OAuth flow</dt>
    <dd><%= link_to "Start", new_facebook_path %></dd>
  </dl>
<% end %>

<fb:like-box profile_id="117513961602338" width="300" connections="6"></fb:like-box>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
  <head>
    <title>FbGraphSample</title>
    <meta property="fb:app_id" content="<%= Facebook.config[:client_id] %>">
    <!--[if IE]>
    <script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag 'base', 'layout', 'gritter', controller_name %>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.js"></script>
    <%= javascript_include_tag 'rails', 'jquery.gritter' %>
    <%= csrf_meta_tag %>
    <%= yield :head %>
  </head>
  <body>
    <div id="fb-root"></div>
    <h1><%= link_to "FbGraph Sample", root_path %></h1>
    <div class="container">
      <div class="main">
        <%= yield %>
      </div>
      <aside class="sidebar">
        <%= render :partial => 'layouts/sidebar' %>
      </aside>
    </div>
    <%= render 'layouts/footer' %>
    <script src="http://connect.facebook.net/en_US/all.js"></script>
    <script>
      FB.init({
        appId: "<%= Facebook.config[:client_id] %>",
        cookie: true,
        xfbml: true,
        oauth: true
      });
    </script>
    <script type="text/javascript">
      $(function () {
        <% if flash[:error] %>
          $.gritter.add({
            title: "<%= flash[:error][:title] %>",
            text : "<%= flash[:error][:message] %>",
            image: "<%= flash[:error][:image] %>",
            time : 5000
          });
        <% elsif flash[:notice] %>
          $.gritter.add({
            title: "<%= flash[:notice][:title] %>",
            text : "<%= flash[:notice][:message] %>",
            image: "<%= flash[:notice][:image] %>",
            time : 3000
          });
        <% end %>
      });
    </script>
  </body>
</html>

app/views/layouts/canvas.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
  <head>
    <title>FbGraphSample</title>
    <meta property="fb:app_id" content="<%= Facebook.config[:client_id] %>">
    <!--[if IE]>
    <script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag 'canvas' %>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.js"></script>
    <%= javascript_include_tag 'rails' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="fb-root"></div>
    <div class="container">
      <div class="main">
        <%= yield %>
      </div>
    </div>
    <script src="http://connect.facebook.net/en_US/all.js"></script>
    <script>
      FB.init({
        appId: "<%= Facebook.config[:client_id] %>",
        cookie: true,
        xfbml: true
      });
    </script>
  </body>
</html>

app/views/profiles/show.html.erb
<section class="profile">
  <h2>User Profile</h2>
  <dl>
    <dt>Username</dt>
    <dd><%= current_user.profile.username %></dd>
    <dt>Name</dt>
    <dd><%= current_user.profile.name %></dd>
    <dt>First Name</dt>
    <dd><%= current_user.profile.first_name %></dd>
    <dt>Middle Name</dt>
    <dd><%= current_user.profile.middle_name %></dd>
    <dt>Last Name</dt>
    <dd><%= current_user.profile.last_name %></dd>
    <dt>Gender</dt>
    <dd><%= current_user.profile.gender %></dd>
    <dt>Link</dt>
    <dd><%= link_to current_user.profile.link, current_user.profile.link %></dd>
    <dt>Email</dt>
    <dd><%= current_user.profile.email %></dd>
    <dt>About</dt>
    <dd><%= current_user.profile.about %></dd>
    <dt>Birthday</dt>
    <dd><%= current_user.profile.birthday %></dd>
    <dt>Work</dt>
    <% current_user.profile.work.each do |work| %>
      <dd>
        <article>
          <header>
            <h3><%= work.employer.name %></h3>
            <p><%= work.start_date %> - <%= work.end_date || 'Current' %></p>
          </header>
          <p><%= work.position.try(:name) %></p>
        </article>
      </dd>
    <% end %>
    <dt>Education</dt>
    <% current_user.profile.education.each do |education| %>
      <dd>
        <article>
          <h3><%= education.school.name %></h3>
          <p><%= education.type %></p>
        </article>
      </dd>
    <% end %>
    <dt>Website</dt>
    <dd><%= simple_format auto_link current_user.profile.website %></dd>
    <dt>Hometown</dt>
    <dd><%= current_user.profile.hometown.try(:name) %></dd>
    <dt>Location</dt>
    <dd><%= current_user.profile.location.try(:name) %></dd>
    <dt>Bio</dt>
    <dd><%= current_user.profile.bio %></dd>
    <dt>Quotes</dt>
    <dd><%= current_user.profile.quotes %></dd>
    <dt>Interested in</dt>
    <dd><%= current_user.profile.interested_in.join(', ') %></dd>
    <dt>Relationship Status</dt>
    <dd><%= current_user.profile.relationship_status %></dd>
    <dt>Religion</dt>
    <dd><%= current_user.profile.religion %></dd>
    <dt>Political</dt>
    <dd><%= current_user.profile.political %></dd>
    <dt>Verified</dt>
    <dd><%= current_user.profile.verified %></dd>
    <dt>Significant Other</dt>
    <dd><%= current_user.profile.significant_other.try(:name) %></dd>
    <dt>Timezone</dt>
    <dd><%= current_user.profile.timezone %></dd>
    <dt>Locale</dt>
    <dd><%= current_user.profile.locale %></dd>
    <dt>Languages</dt>
    <dd><%= current_user.profile.languages.collect(&:name).join(', ') %></dd>
    <dt>Sports</dt>
    <dd><%= current_user.profile.sports.collect(&:name).join(', ') %></dd>
    <dt>Favorite Teams</dt>
    <dd><%= current_user.profile.favorite_teams.collect(&:name).join(', ') %></dd>
    <dt>Inspirational People</dt>
    <dd><%= current_user.profile.inspirational_people.collect(&:name).join(', ') %></dd>
    <dt>Update Time</dt>
    <dd><%= current_user.profile.updated_time %></dd>
    <dt>Third Party ID</dt>
    <dd><%= current_user.profile.third_party_id %></dd>
    <dt>Pending.. (temporary disabled by facebook)</dt>
    <% [:address, :mobile_phone].each do |attribute| %>
      <dd><%= attribute %></dd>
    <% end %>
  </dl>
</section>

app/views/subscriptions/_form.html.erb
<%= form_for Subscription.new, :url => subscriptions_path do |f| %>
  <p>
    <%= f.label :object %>
    <%= f.select :object, [:user, :permissions, :page] %>
  </p>
  <p>
    <%= f.label :fields %>
    <%= f.text_field :fields, :placeholder => 'field1, field2, ..' %>
  </p>
  <%= f.submit %>
  <aside>
    <h3>NOTE</h3>
    <p>You'll need at least 2 server process running.</p>
    <p>This sample app on heroku.com has only 1 process running.</p>
    <p>Please setup your server to test subscriptions.</p>
  </aside>
<% end %>

app/views/subscriptions/_subscription.html.erb
<article>
  <h2><%= subscription.object %></h2>
  <p><%= subscription.fields %></p>
  <ul>
    <% subscription.history.each do |update| %>
      <li>
        <pre><%= JSON.pretty_generate update %></pre>
      </li>
    <% end %>
  </ul>
</article>

app/views/subscriptions/index.html.erb
<section>
  <h1>Subscriptions</h1>
  <nav>
    <%= render 'subscriptions/form' %>
  </nav>
  <%= render current_user.subscriptions %>
</section>

app/views/timeline/show.html.erb
<section class="timeline">
  <% form_tag timeline_path do %>
    <%= text_area_tag :message, nil, :placeholder => 'Message here.' %>
    <%= submit_tag 'Update', :disable_with => 'Updating...' %>
  <% end %>
  <% @posts.each do |post| %>
    <article class="clearfix">
      <div class="avatar">
        <fb:profile-pic uid="<%= post.from.identifier %>" size="square"></fb:profile-pic>
      </div>
      <p>
        <strong><fb:name uid="<%= post.from.identifier %>"></fb:name></strong>
        <%= post.message || post.name || post.caption || post.description %>
      </p>
    </article>
  <% end %>
</section>

app/views/top/index.html.erb
<section class="top">
  <article>
    <h2>Learn how to use <%= link_to "fb_graph", fb_graph_url %>!</h2>
    <p><%= link_to "fb_graph", fb_graph_url %> is a full-stack Facebook Graph API wrapper in Ruby.</p>
    <p>Reading the souce code (in Rails), you can learn how to authenticate facebook users using <%= link_to "fb_graph", fb_graph_url %>, how to access their profile data, how to update their status etc.</p>
    <footer>
      <p>NOTE: This application requires all permissions Graph API supports. If you hesitate to allow them, download source code and edit config/facebook.yml</p>
    </footer>
  </article>

  <article>
    <h2>Source Code</h2>
    <ul>
      <li><%= link_to 'fg_graph', fb_graph_url %></li>
      <li><%= link_to 'this sample app (Rails)', fb_graph_sample_url %></li>
    </ul>
  </article>
</section>